
server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: devp
  webflux:
    date-format: yyyy-MM-dd
  application:
    name: boo
  thymeleaf:
    prefix: 'classpath:/templates/'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      db-type: mysql
      initial-size: 10
      max-active: 200
      min-idle: 10
      validation-query: select 1
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 100
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
  redis:
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 100
        max-idle: 20
        min-idle: 10

logging:
  path: /home/log/boo
  level:
    com:
      dd: info
