
logging:
  path: /Users/${user.name}/home/log/boo
  level:
    com:
      dd: debug

spring:
  datasource:
    druid:
      name: boo
      url: jdbc:mysql://localhost:3306/boo?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: